# Project information .........................................
site_name: "Model Mondays"
site_url: https://microsoft.github.io/model-mondays
site_author: Nitya Narasimhan
site_description: >-
 Model Mondays helps AI developers build model expertise through practical spotlights and on-demand expert AMAs.

# Repository ..................................................
repo_name: microsoft/model-mondays
repo_url: https://github.com/microsoft/model-mondays

# Copyright ...................................................
copyright: >
  &copy; 2025 Microsoft &nbsp;|&nbsp;
  <a href="https://go.microsoft.com/fwlink/?LinkId=521839">Privacy </a>&nbsp;|&nbsp;
  <a href="https://go.microsoft.com/fwlink/?LinkId=2259814">Consumer Health Privacy </a>&nbsp;|&nbsp;
  <a href="https://go.microsoft.com/fwlink/?LinkID=206977">Terms of Use </a>&nbsp;|&nbsp;
  <a href="https://www.microsoft.com/trademarks">Trademarks </a>


# Configuration ...............................................
theme:
  name: material
  font:
    code: Roboto Mono  #Monospaced
    text: Roboto       #Regular
  logo: assets/misc/mm-flames.png
  language: en

  # Theme Modes ...............................................
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  # Theme Features ...............................................
  features:
    - navigation.instant
    - navigation.expand             # sidebar collapsible sections open
    - navigation.instant.progress   # load progress indicator
    - navigation.tracking           # tracks anchor tags in URL
    - navigation.tabs               # tabbed on desktop, single in mobile    
    - navigation.tabs.sticky
    - navigation.path               # add breadcrumbs
    - navigation.indexes            # index.md is default page for section
    - navigation.top
    - toc.follow
    - navigation.footer
    - content.code.copy             # allow copy-paste from codeblocks
    - content.tabs.link             # Ensures site-wide switch to same tab name

# Extras  ...............................................
extra:
  generator: false

# Plugins  ...............................................
plugins:
  - search
  - blog:
      categories_allowed:
        - Recaps
        - Tutorials
        - Season-01
        - Season-02
        - Season-03
        - Season-04
  - tags

# Extensions  ...............................................
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      auto_title: true
      linenums: true
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower


# Navigation  ...............................................
nav:
  - Overview: index.md
  - Season 4:
    - 01 | MAI Models: model-mondays/2026-08-10-s04-e01.md
    - 02 | Cohere: model-mondays/2026-08-17-s04-e02.md
    - 03 | Model Router: model-mondays/2026-08-24-s04-e03.md
    - 04 | Research Models: model-mondays/2026-08-31-s04-e04.md
    - 05 | Claude Models: model-mondays/2026-09-14-s04-e05.md
    - 06 | Azure OpenAI: model-mondays/2026-09-21-s04-e06.md
    - 07 | Mistral: model-mondays/2026-09-28-s04-e07.md
    - 08 | Fine-Tuned Models: model-mondays/2026-10-05-s04-e08.md
    - 09 | Speech Models: model-mondays/2026-10-12-s04-e09.md
    - 10 | Hugging Face: model-mondays/2026-10-19-s04-e10.md
    - 11 | Open Models: model-mondays/2026-10-26-s04-e11.md
    - 12 | NVIDIA Models: model-mondays/2026-11-02-s04-e12.md
  - Foundry Friday AMAs: foundry-fridays/README.md
  - Customer Stories: customer-stories/README.md
  - Hugging Face: hugging-face/README.md
  - Blog:
    - blog/index.md
    - Tags: blog/tags.md
